"""empty message

Revision ID: 43bb4d023825
Revises:
Create Date: 2022-08-03 22:10:47.394995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bb4d023825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('city',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(length=120), nullable=False),
	sa.Column('state', sa.String(length=120), nullable=True),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('genre',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(length=120), nullable=False),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('Artist',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(), nullable=True),
	sa.Column('phone', sa.String(length=120), nullable=True),
	sa.Column('image_link', sa.String(length=500), nullable=True),
	sa.Column('facebook_link', sa.String(length=120), nullable=True),
	sa.Column('city_id', sa.Integer(), nullable=False),
	sa.Column('website', sa.String(length=120), nullable=True),
	sa.Column('seeking_venue', sa.Boolean(), nullable=False),
	sa.Column('seeking_description', sa.String(), nullable=True),
	sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('Venue',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(), nullable=True),
	sa.Column('address', sa.String(length=120), nullable=True),
	sa.Column('phone', sa.String(length=120), nullable=True),
	sa.Column('image_link', sa.String(length=500), nullable=True),
	sa.Column('facebook_link', sa.String(length=120), nullable=True),
	sa.Column('city_id', sa.Integer(), nullable=False),
	sa.Column('website', sa.String(length=120), nullable=True),
	sa.Column('seeking_talent', sa.Boolean(), nullable=False),
	sa.Column('seeking_description', sa.String(), nullable=True),
	sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('Show',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('start_time', sa.String(length=50), nullable=True),
	sa.Column('venue_id', sa.Integer(), nullable=False),
	sa.Column('artist_id', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
	sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('artist_genres',
	sa.Column('artist_id', sa.Integer(), nullable=False),
	sa.Column('genre_id', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
	sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
	sa.PrimaryKeyConstraint('artist_id', 'genre_id')
	)
	op.create_table('venue_genres',
	sa.Column('venue_id', sa.Integer(), nullable=False),
	sa.Column('genre_id', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
	sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
	sa.PrimaryKeyConstraint('venue_id', 'genre_id')
	)

	# Populate data

	# CITY:

	op.execute("insert into \"city\" (name, state) values ('San Fancisco', 'CA');")
	op.execute("insert into \"city\" (name, state) values ('New York', 'NY');")

	# VENUE:

	op.execute("insert into \"Venue\" (name, address, city_id, phone, website, facebook_link, seeking_talent, seeking_description, image_link) values ('The Musical Hop', '1015 Folsom Street', 1, '123-123-1234', 'https://www.themusicalhop.com', 'https://www.facebook.com/TheMusicalHop', True, 'We are on the lookout for a local artist to play every two weeks. Please call us.', 'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60');")

	op.execute("insert into \"Venue\" (name, address, city_id, phone, website, facebook_link, seeking_talent, image_link) values ('The Dueling Pianos Bar', '335 Delancey Street', 2, '914-003-1132', 'https://www.theduelingpianos.com', 'https://www.facebook.com/theduelingpianos', False, 'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80');")

	op.execute("insert into \"Venue\" (name, address, city_id, phone, website, facebook_link, seeking_talent, image_link) values ('Park Square Live Music & Coffee', '34 Whiskey Moore Ave', 1, '415-000-1234', 'https://www.parksquarelivemusicandcoffee.com', 'https://www.facebook.com/ParkSquareLiveMusicAndCoffee', False, 'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80');")

	# ARTIST:

	op.execute("insert into \"Artist\" (id, name, city_id, phone, website, facebook_link, seeking_venue, seeking_description, image_link) values (4, 'Guns N Petals', 1, '326-123-5000', 'https://www.gunsnpetalsband.com', 'https://www.facebook.com/GunsNPetals', True, 'Looking for shows to perform at in the San Francisco Bay Area!', 'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80');")

	op.execute("insert into \"Artist\" (id, name, city_id, phone, facebook_link, seeking_venue, image_link) values (5, 'Matt Quevedo', 2, '300-400-5000', 'https://www.facebook.com/mattquevedo923251523', False, 'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80');")

	op.execute("insert into \"Artist\" (id, name, city_id, phone, seeking_venue, image_link) values (6, 'The Wild Sax Band', 1, '432-325-5432', False, 'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80');")

	# SHOW

	op.execute("insert into \"Show\" (venue_id, artist_id, start_time) values (1, 4, '2019-05-21T21:30:00.000Z');")

	op.execute("insert into \"Show\" (venue_id, artist_id, start_time) values (3, 5, '2019-06-15T23:00:00.000Z');")

	op.execute("insert into \"Show\" (venue_id, artist_id, start_time) values (3, 6, '2035-04-01T20:00:00.000Z');")

	op.execute("insert into \"Show\" (venue_id, artist_id, start_time) values (3, 6, '2035-04-08T20:00:00.000Z');")

	op.execute("insert into \"Show\" (venue_id, artist_id, start_time) values (3, 6, '2035-04-15T20:00:00.000Z');")

	# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genres')
    op.drop_table('artist_genres')
    op.drop_table('Show')
    op.drop_table('Venue')
    op.drop_table('Artist')
    op.drop_table('genre')
    op.drop_table('city')
    # ### end Alembic commands ###
